### PR TITLE
Updated E2 machine profile

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@jorgerobles Pls check nothing is broken. thank you.

**Comment by jorgerobles** [comment]
Done!

**Comment by ghost** [comment]
thx!

**Comment by jorgerobles** [comment]
I'm going to think around splitting vendor files as the .md case. That way will be a lot better to debug profiles. Then machine-profiles will only hold the index of machines pointing to other smaller files.

**Comment by ghost** [comment]
This is a very good idea.
That way we can also ensure updating one vendor's profile doesn't break another vendor's etc.

**Comment by ghost** [comment]
Also, are there any legacy settings in the current version of the machine-profile that no longer apply?

It would be very handy to know everything that can be added to a machine profile. Is this information available somewhere?

**Comment by jorgerobles** [comment]
Yes, that should come with json schema validator, so any legacy will be warned to be erased (hope to figure out soon)

**Pull request merged**
